### PR TITLE
#158239979 Create rides given page

### PR DESCRIPTION
**Pull request by micahoriaso**
**What does this PR do?**
Create the rides gievn page

**Description of the task to be completed**
Build the user interface elements for the rides given page

**How to manually test**
* Clone the repo and cd into it.
* checkout into ft-rides-given-158239979 branch
* cd into the UI folder
* open rides-given
.html with a browser

**Relevant pivotal tracker stories**
#158239979

**Screenshots**
fireshot capture 011 - rides given_ - file____home_oriaso_desktop_python

### CODE REVIEW

**Comment by micahoriaso** [comment]
@wandesky, @derrickkip check this baby out.

**Comment by Darius-Ndubi** [comment]
Nice design, would suggest making the footer fixed at page bottom.

**Comment by micahoriaso** [comment]
Thanks @Darius-Ndubi let me work on a fix

**Comment by micahoriaso** [comment]
@Darius-Ndubi footer position fixed

**Comment by Derrickkip** [comment]
Great design love the simplicity

**Comment by micahoriaso** [comment]
Thanks @Derrickkip. I'll now perform the merge

**Pull request merged**
