### PR TITLE
#158239847 Create ride requests page

### PR DESCRIPTION
**Pull request by micahoriaso**
**What does this PR do?**
Create  ride requests page
**Description of the task to be completed**
Build the user interface elements for ride request page

**How should this be manually tested?**
* Clone the repo and cd into it.
* checkout into ft-offer-ride-page-158239847 branch
* cd into the UI folder
* open ride-requests.html with a browser

**What are the relevant pivotal tracker stories?**
#158239847

**Screenshots**
fireshot capture 006 - ride requests_ - file____home_oriaso_desktop_python

### CODE REVIEW

**Comment by micahoriaso** [comment]
@Teddykavooh,  @Derrickkip what do you think about this?

**Comment by Derrickkip** [comment]
Awesome design

**Comment by micahoriaso** [comment]
Thank @Derrickkip I'll do a merge now.

**Comment by Teddykavooh** [comment]
All content is covered.Nice work but it looks kind of bulky.Can the route and time be part of the smaller table?

**Pull request merged**
