### PR TITLE
#158239774 Create available ride offers list

### PR DESCRIPTION
**Pull request by micahoriaso**
**What does this PR do?**
Create an available ride offers list template

**Description of the task to be completed**
Build the user interface elements for the available ride offers page

**How should this be manually tested?**
* Clone the repo and cd into it.
* checkout into ft-ride-offers-list-158239774 branch
* cd into the UI folder
* open ride-offers.html with a browser

**What are the relevant pivotal tracker stories?**
#158239774

**Screenshots**
fireshot capture 001 - ride offers_ - file____home_oriaso_desktop_python

### CODE REVIEW

**Comment by micahoriaso** [comment]
Kindly consider these updates. Your feedback is massively appreciated
@Lemmah, @mikenthiwa, @Teddykavooh @byarustev @PAbishai

**Comment by meshack-mbuvi** [comment]
You should probably add screenshot of the page as rendered on the browser.This way,we can be able to easily see what it's all about.

**Comment by micahoriaso** [comment]
fireshot capture 001 - ride offers_ - file____home_oriaso_desktop_python
Hi, @meshack-mbuvi screenshot delivered just as requested.

**Comment by meshack-mbuvi** [comment]
I think this is ok.

**Comment by byarustev** [comment]
It looks good. I think it's fine.

Sorry about not responding earlier. I have been offline.

**Comment by Derrickkip** [comment]
looks good :+1:

**Comment by pabishai** [comment]
I think its OK based on the current instructions

**Comment by Teddykavooh** [comment]
Well covered

**Pull request merged**
