### PR TITLE
#158459164 Create ride offers REST api endpoint

### PR DESCRIPTION
**Pull request by micahoriaso**
**What does this PR do?**
Creates a REST api endpoint for list of ride offers

**Description of the task to be completed**
Build a REST api endpoint to GET a list of all ride offers

**How to manually test**
* Clone the repo and cd into it.
* Checkout into ft-ride-offers-api-158459164 branch
* Create a virtual environment and activate it
```
python3 -m venv venv
source venv/bin/activate
```
* Install all dependencies

```
pip install -r requirements.txt
```
* Run the Flask application
```
set FLASK_APP=flaskr
set FLASK_ENV=development
flask run
```
* Open [http://127.0.0.1:5000/api/v1/rides/](http://127.0.0.1:5000/api/v1/rides/) in a browser or Postman

**Relevant pivotal tracker stories**
[#158459164/](https://www.pivotaltracker.com/n/projects/2177712)

**Screenshots**
fireshot capture 14 - - http___127 0 0 1_5000_api_v1_rides_

### CODE REVIEW

**Comment by micahoriaso** [comment]
Hi @Derrickkip, @wandesky please review my updates

**Comment by Derrickkip** [comment]
@micahoriaso It looks okay, how many resources are you going to have?

**Comment by Derrickkip** [comment]
Noticed you've not integrated TravisCI, its best to have done that so that when you push code with tests you get coverage reporting early on

**Comment by micahoriaso** [comment]
I've now integrated continuous testing and test coverage reporting.

**Comment by micahoriaso** [comment]
@Derrickkip Initially I didn't understand what you meant by resource but upon implementing flask-restful I have understood. I am going to have just a single resource for rides. It will cater for the minimal requirements of the challenge. Once that is done then I'll consider other possible resources.

**Pull request merged**
