### PR TITLE
#158353989 Create edit profile page

### PR DESCRIPTION
**Pull request by micahoriaso**
**What does this PR do?**
Create the edit profile page

**Description of the task to be completed**
Build the user interface elements for the edit profile page

**How to manually test**
* Clone the repo and cd into it.
* checkout into ft-edit-profile-158353989 branch
* cd into the UI folder
* open edit-profile.html with a browser

**Relevant pivotal tracker stories**
#158353989

**Screenshots**
fireshot capture 015 - ride detail_ - file____home_oriaso_desktop_python

### CODE REVIEW

**Comment by micahoriaso** [comment]
Apologies @wandesky and @Derrickkip. I know your inbox is blowing up with pull request. Here is one more for your review

**Comment by Derrickkip** [comment]
@micahoriaso no problem we scratch each others backs, nice design the consistency in the pages is commendable, I am thinking of having at most two pages for the profile section one for user details and one for rides given and taken what do you think?

**Comment by micahoriaso** [comment]
@Derrickkip this is what I have with mine. https://user-images.githubusercontent.com/20840601/41377320-6472fa3e-6f64-11e8-9a09-fcbdfd4eb886.png

Since the user profile doesn't have much content to start with, I added shortened lists or rides given and taken. There are more buttons under each which in turn take you to the full list of each.

**Comment by Derrickkip** [comment]
Thanks i'll also go with that and have a different page for editing user details and another one to view complete details ride but I plan to have the rides given and taken on the same page

**Comment by micahoriaso** [comment]
There is no harm in that. Go for it, I can't wait to see what you come up with

**Pull request merged**
